Make bins a little better

diff --git a/bin/normalize-configuration b/bin/normalize-configuration
--- a/bin/normalize-configuration
+++ b/bin/normalize-configuration
@@ -1,22 +1,31 @@
 #!/usr/bin/env bash
-if [ -z  "$HAL_ENVIRONMENT" ] ; then
+
+# configure
+set -e
+set -u
+
+# declare variables
+p_DIR=$( cd "$( dirname "$0" )" && pwd )
+p_HAL_ENVIRONMENT="${HAL_ENVIRONMENT:=}"
+
+if [ -z  "$p_HAL_ENVIRONMENT" ] ; then
     echo "HAL 9000 environment not found. Using development configuration."
-    HAL_ENVIRONMENT="dev"
+    p_HAL_ENVIRONMENT="dev"
 fi
 
-DIR=$( cd "$( dirname "$0" )" && pwd )
-TARGET_CONFIG="config.env.yml"
-NORMALIZED_ENV=$(echo "$HAL_ENVIRONMENT" | tr "[:upper:]" "[:lower:]")
-CONFIG="$NORMALIZED_ENV.yml"
+p_NORMALIZED_ENV=$(echo "$p_HAL_ENVIRONMENT" | tr "[:upper:]" "[:lower:]")
+p_TARGET_CONFIG="config.env.yml"
+p_CONFIG="$p_NORMALIZED_ENV.yml"
 
-echo "Current environment: $HAL_ENVIRONMENT"
-echo "Normalized environment: $NORMALIZED_ENV"
+# script
+echo "Current environment: $p_HAL_ENVIRONMENT"
+echo "Normalized environment: $p_NORMALIZED_ENV"
 
-EXISTS=$(test -e $DIR/../configuration/environment/$CONFIG && echo 1 || echo 0)
-if [[ $EXISTS -eq "1" ]]; then
-    echo "Configuration found: $CONFIG"
-    echo "Overwriting $TARGET_CONFIG"
-    cat "$DIR/../configuration/environment/$CONFIG" > "$DIR/../configuration/config.env.yml"
+p_EXISTS=$(test -e $p_DIR/../configuration/environment/$p_CONFIG && echo 1 || echo 0)
+if [[ $p_EXISTS -eq "1" ]]; then
+    echo "Configuration found: $p_CONFIG"
+    echo "Overwriting $p_TARGET_CONFIG"
+    cat "$p_DIR/../configuration/environment/$p_CONFIG" > "$p_DIR/../configuration/config.env.yml"
 else
-    echo "Configuration not found: $CONFIG"
+    echo "Configuration not found: $p_CONFIG"
 fi
